challenge:
	cat input.txt | cargo run --manifest-path 1/Cargo.toml --quiet -- 9000
	cat input.txt | cargo run --manifest-path 1/Cargo.toml --quiet -- 9001

test:
	cat test.txt | cargo run --manifest-path 1/Cargo.toml --quiet -- 9000
	cat test.txt | cargo run --manifest-path 1/Cargo.toml --quiet -- 9001
