challenge:
	cat input.txt | cargo run --manifest-path 1/Cargo.toml --quiet
	cat input.txt | cargo run --manifest-path 1/Cargo.toml --quiet -- 14

test:
	cat test.txt | cargo run --manifest-path 1/Cargo.toml --quiet
	cat test.txt | cargo run --manifest-path 1/Cargo.toml --quiet -- 14
