challenge:
	cat input.txt | cargo run --manifest-path 1/Cargo.toml --quiet
	cat input.txt | cargo run --manifest-path 2/Cargo.toml --quiet

test:
	cat test.txt | cargo run --manifest-path 1/Cargo.toml --quiet
	cat test.txt | cargo run --manifest-path 2/Cargo.toml --quiet

